#import "presets.typ": *
#show: template.with(doc_title: "PHYS 161 Notes", numbering_depth: 2)

#include("ch_1.typ")
#include("ch_2.typ")
#include("ch_3.typ")
#include("ch_4.typ")
#include("ch_5.typ")
#include("ch_6.typ")
#include("ch_7.typ")
#include("ch_8.typ")
#include("ch_9.typ")
#include("ch_10.typ")
#include("ch_11.typ")
#include("ch_14.typ")