#import "../../presets.typ": *
#show: template.with(doc_title: "PHYS 161 Notes", doc_subtitle: "Mechanics and Heat", show_title: true, show_header: true,  numbering_depth: 2, math_font: "XITS Math")

#include("ch_1.typ")
#include("ch_2.typ")
#include("ch_3.typ")
#include("ch_4.typ")
#include("ch_5.typ")
#include("ch_6.typ")
#include("ch_7.typ")
#include("ch_8.typ")
#include("ch_9.typ")
#include("ch_10.typ")
#include("ch_11.typ")
#include("ch_14.typ")